/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq;


import io.exflo.postgres.jooq.tables.Account;
import io.exflo.postgres.jooq.tables.BalanceDelta;
import io.exflo.postgres.jooq.tables.BlockHeader;
import io.exflo.postgres.jooq.tables.ContractCreated;
import io.exflo.postgres.jooq.tables.ContractDestroyed;
import io.exflo.postgres.jooq.tables.ContractEvent;
import io.exflo.postgres.jooq.tables.FlywaySchemaHistory;
import io.exflo.postgres.jooq.tables.ImportQueue;
import io.exflo.postgres.jooq.tables.Metadata;
import io.exflo.postgres.jooq.tables.Ommer;
import io.exflo.postgres.jooq.tables.Transaction;
import io.exflo.postgres.jooq.tables.TransactionReceipt;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PKEY = Indexes0.ACCOUNT_PKEY;
    public static final Index IDX_ACCOUNT__ADDRESS = Indexes0.IDX_ACCOUNT__ADDRESS;
    public static final Index IDX_ACCOUNT__BLOCK_HASH = Indexes0.IDX_ACCOUNT__BLOCK_HASH;
    public static final Index IDX_ACCOUNT__BLOCK_NUMBER = Indexes0.IDX_ACCOUNT__BLOCK_NUMBER;
    public static final Index BALANCE_DELTA_PKEY = Indexes0.BALANCE_DELTA_PKEY;
    public static final Index IDX_BALANCE_DELTA__BLOCK_NUMBER_DESC = Indexes0.IDX_BALANCE_DELTA__BLOCK_NUMBER_DESC;
    public static final Index IDX_BALANCE_DELTA__TRANSACTION_HASH = Indexes0.IDX_BALANCE_DELTA__TRANSACTION_HASH;
    public static final Index BLOCK_HEADER_PKEY = Indexes0.BLOCK_HEADER_PKEY;
    public static final Index IDX_BLOCK_HEADER__NUMBER_DESC = Indexes0.IDX_BLOCK_HEADER__NUMBER_DESC;
    public static final Index CONTRACT_CREATED_PKEY = Indexes0.CONTRACT_CREATED_PKEY;
    public static final Index IDX_CONTRACT_CREATED__ADDRESS = Indexes0.IDX_CONTRACT_CREATED__ADDRESS;
    public static final Index IDX_CONTRACT_CREATED__BLOCK_NUMBER_DESC = Indexes0.IDX_CONTRACT_CREATED__BLOCK_NUMBER_DESC;
    public static final Index CONTRACT_DESTROYED_PKEY = Indexes0.CONTRACT_DESTROYED_PKEY;
    public static final Index IDX_CONTRACT_DESTROYED__ADDRESS = Indexes0.IDX_CONTRACT_DESTROYED__ADDRESS;
    public static final Index IDX_CONTRACT_DESTROYED__BLOCK_HASH = Indexes0.IDX_CONTRACT_DESTROYED__BLOCK_HASH;
    public static final Index IDX_CONTRACT_DESTROYED__BLOCK_NUMBER_DESC = Indexes0.IDX_CONTRACT_DESTROYED__BLOCK_NUMBER_DESC;
    public static final Index IDX_CONTRACT_DESTROYED__TRANSACTION_HASH = Indexes0.IDX_CONTRACT_DESTROYED__TRANSACTION_HASH;
    public static final Index IDX_CONTRACT_EVENT__BLOCK_NUMBER_DESC = Indexes0.IDX_CONTRACT_EVENT__BLOCK_NUMBER_DESC;
    public static final Index IDX_CONTRACT_EVENT__TRANSACTION_HASH = Indexes0.IDX_CONTRACT_EVENT__TRANSACTION_HASH;
    public static final Index IDX_EVENT_TYPE = Indexes0.IDX_EVENT_TYPE;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index IDX_IMPORT_QUEUE__HASH = Indexes0.IDX_IMPORT_QUEUE__HASH;
    public static final Index IMPORT_QUEUE_HASH_KEY = Indexes0.IMPORT_QUEUE_HASH_KEY;
    public static final Index IMPORT_QUEUE_PKEY = Indexes0.IMPORT_QUEUE_PKEY;
    public static final Index METADATA_PKEY = Indexes0.METADATA_PKEY;
    public static final Index IDX_OMMER__HASH = Indexes0.IDX_OMMER__HASH;
    public static final Index IDX_OMMER__HEIGHT = Indexes0.IDX_OMMER__HEIGHT;
    public static final Index IDX_OMMER__INDEX = Indexes0.IDX_OMMER__INDEX;
    public static final Index IDX_OMMER__NEPHEW_HASH = Indexes0.IDX_OMMER__NEPHEW_HASH;
    public static final Index IDX_OMMER__NUMBER_DESC = Indexes0.IDX_OMMER__NUMBER_DESC;
    public static final Index OMMER_PKEY = Indexes0.OMMER_PKEY;
    public static final Index IDX_TRANSACTION__BLOCK_HASH = Indexes0.IDX_TRANSACTION__BLOCK_HASH;
    public static final Index IDX_TRANSACTION__INDEX_ASC = Indexes0.IDX_TRANSACTION__INDEX_ASC;
    public static final Index IDX_TRANSACTION__NUMBER_DESC = Indexes0.IDX_TRANSACTION__NUMBER_DESC;
    public static final Index TRANSACTION_PKEY = Indexes0.TRANSACTION_PKEY;
    public static final Index IDX_TRANSACTION_RECEIPT__NUMBER_DESC = Indexes0.IDX_TRANSACTION_RECEIPT__NUMBER_DESC;
    public static final Index IDX_TRANSACTION_RECEIPT__TRANSACTION_HASH = Indexes0.IDX_TRANSACTION_RECEIPT__TRANSACTION_HASH;
    public static final Index TRANSACTION_RECEIPT_PKEY = Indexes0.TRANSACTION_RECEIPT_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PKEY = Internal.createIndex("account_pkey", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ADDRESS, Account.ACCOUNT.BLOCK_HASH }, true);
        public static Index IDX_ACCOUNT__ADDRESS = Internal.createIndex("idx_account__address", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ADDRESS }, false);
        public static Index IDX_ACCOUNT__BLOCK_HASH = Internal.createIndex("idx_account__block_hash", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.BLOCK_HASH }, false);
        public static Index IDX_ACCOUNT__BLOCK_NUMBER = Internal.createIndex("idx_account__block_number", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.BLOCK_NUMBER }, false);
        public static Index BALANCE_DELTA_PKEY = Internal.createIndex("balance_delta_pkey", BalanceDelta.BALANCE_DELTA, new OrderField[] { BalanceDelta.BALANCE_DELTA.ID }, true);
        public static Index IDX_BALANCE_DELTA__BLOCK_NUMBER_DESC = Internal.createIndex("idx_balance_delta__block_number_desc", BalanceDelta.BALANCE_DELTA, new OrderField[] { BalanceDelta.BALANCE_DELTA.BLOCK_NUMBER.desc() }, false);
        public static Index IDX_BALANCE_DELTA__TRANSACTION_HASH = Internal.createIndex("idx_balance_delta__transaction_hash", BalanceDelta.BALANCE_DELTA, new OrderField[] { BalanceDelta.BALANCE_DELTA.TRANSACTION_HASH }, false);
        public static Index BLOCK_HEADER_PKEY = Internal.createIndex("block_header_pkey", BlockHeader.BLOCK_HEADER, new OrderField[] { BlockHeader.BLOCK_HEADER.HASH }, true);
        public static Index IDX_BLOCK_HEADER__NUMBER_DESC = Internal.createIndex("idx_block_header__number_desc", BlockHeader.BLOCK_HEADER, new OrderField[] { BlockHeader.BLOCK_HEADER.NUMBER.desc() }, false);
        public static Index CONTRACT_CREATED_PKEY = Internal.createIndex("contract_created_pkey", ContractCreated.CONTRACT_CREATED, new OrderField[] { ContractCreated.CONTRACT_CREATED.ADDRESS, ContractCreated.CONTRACT_CREATED.TRANSACTION_HASH }, true);
        public static Index IDX_CONTRACT_CREATED__ADDRESS = Internal.createIndex("idx_contract_created__address", ContractCreated.CONTRACT_CREATED, new OrderField[] { ContractCreated.CONTRACT_CREATED.ADDRESS }, false);
        public static Index IDX_CONTRACT_CREATED__BLOCK_NUMBER_DESC = Internal.createIndex("idx_contract_created__block_number_desc", ContractCreated.CONTRACT_CREATED, new OrderField[] { ContractCreated.CONTRACT_CREATED.BLOCK_NUMBER.desc() }, false);
        public static Index CONTRACT_DESTROYED_PKEY = Internal.createIndex("contract_destroyed_pkey", ContractDestroyed.CONTRACT_DESTROYED, new OrderField[] { ContractDestroyed.CONTRACT_DESTROYED.ADDRESS, ContractDestroyed.CONTRACT_DESTROYED.TRANSACTION_HASH }, true);
        public static Index IDX_CONTRACT_DESTROYED__ADDRESS = Internal.createIndex("idx_contract_destroyed__address", ContractDestroyed.CONTRACT_DESTROYED, new OrderField[] { ContractDestroyed.CONTRACT_DESTROYED.ADDRESS }, false);
        public static Index IDX_CONTRACT_DESTROYED__BLOCK_HASH = Internal.createIndex("idx_contract_destroyed__block_hash", ContractDestroyed.CONTRACT_DESTROYED, new OrderField[] { ContractDestroyed.CONTRACT_DESTROYED.BLOCK_HASH }, false);
        public static Index IDX_CONTRACT_DESTROYED__BLOCK_NUMBER_DESC = Internal.createIndex("idx_contract_destroyed__block_number_desc", ContractDestroyed.CONTRACT_DESTROYED, new OrderField[] { ContractDestroyed.CONTRACT_DESTROYED.BLOCK_NUMBER.desc() }, false);
        public static Index IDX_CONTRACT_DESTROYED__TRANSACTION_HASH = Internal.createIndex("idx_contract_destroyed__transaction_hash", ContractDestroyed.CONTRACT_DESTROYED, new OrderField[] { ContractDestroyed.CONTRACT_DESTROYED.TRANSACTION_HASH }, false);
        public static Index IDX_CONTRACT_EVENT__BLOCK_NUMBER_DESC = Internal.createIndex("idx_contract_event__block_number_desc", ContractEvent.CONTRACT_EVENT, new OrderField[] { ContractEvent.CONTRACT_EVENT.BLOCK_NUMBER.desc() }, false);
        public static Index IDX_CONTRACT_EVENT__TRANSACTION_HASH = Internal.createIndex("idx_contract_event__transaction_hash", ContractEvent.CONTRACT_EVENT, new OrderField[] { ContractEvent.CONTRACT_EVENT.TRANSACTION_HASH }, false);
        public static Index IDX_EVENT_TYPE = Internal.createIndex("idx_event_type", ContractEvent.CONTRACT_EVENT, new OrderField[] { ContractEvent.CONTRACT_EVENT.TYPE }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index IDX_IMPORT_QUEUE__HASH = Internal.createIndex("idx_import_queue__hash", ImportQueue.IMPORT_QUEUE, new OrderField[] { ImportQueue.IMPORT_QUEUE.HASH }, false);
        public static Index IMPORT_QUEUE_HASH_KEY = Internal.createIndex("import_queue_hash_key", ImportQueue.IMPORT_QUEUE, new OrderField[] { ImportQueue.IMPORT_QUEUE.HASH }, true);
        public static Index IMPORT_QUEUE_PKEY = Internal.createIndex("import_queue_pkey", ImportQueue.IMPORT_QUEUE, new OrderField[] { ImportQueue.IMPORT_QUEUE.NUMBER, ImportQueue.IMPORT_QUEUE.HASH }, true);
        public static Index METADATA_PKEY = Internal.createIndex("metadata_pkey", Metadata.METADATA, new OrderField[] { Metadata.METADATA.KEY }, true);
        public static Index IDX_OMMER__HASH = Internal.createIndex("idx_ommer__hash", Ommer.OMMER, new OrderField[] { Ommer.OMMER.HASH }, false);
        public static Index IDX_OMMER__HEIGHT = Internal.createIndex("idx_ommer__height", Ommer.OMMER, new OrderField[] { Ommer.OMMER.HEIGHT }, false);
        public static Index IDX_OMMER__INDEX = Internal.createIndex("idx_ommer__index", Ommer.OMMER, new OrderField[] { Ommer.OMMER.INDEX }, false);
        public static Index IDX_OMMER__NEPHEW_HASH = Internal.createIndex("idx_ommer__nephew_hash", Ommer.OMMER, new OrderField[] { Ommer.OMMER.NEPHEW_HASH }, false);
        public static Index IDX_OMMER__NUMBER_DESC = Internal.createIndex("idx_ommer__number_desc", Ommer.OMMER, new OrderField[] { Ommer.OMMER.NUMBER.desc() }, false);
        public static Index OMMER_PKEY = Internal.createIndex("ommer_pkey", Ommer.OMMER, new OrderField[] { Ommer.OMMER.HASH }, true);
        public static Index IDX_TRANSACTION__BLOCK_HASH = Internal.createIndex("idx_transaction__block_hash", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.BLOCK_HASH }, false);
        public static Index IDX_TRANSACTION__INDEX_ASC = Internal.createIndex("idx_transaction__index_asc", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.INDEX }, false);
        public static Index IDX_TRANSACTION__NUMBER_DESC = Internal.createIndex("idx_transaction__number_desc", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.BLOCK_NUMBER.desc() }, false);
        public static Index TRANSACTION_PKEY = Internal.createIndex("transaction_pkey", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.HASH }, true);
        public static Index IDX_TRANSACTION_RECEIPT__NUMBER_DESC = Internal.createIndex("idx_transaction_receipt__number_desc", TransactionReceipt.TRANSACTION_RECEIPT, new OrderField[] { TransactionReceipt.TRANSACTION_RECEIPT.BLOCK_NUMBER.desc() }, false);
        public static Index IDX_TRANSACTION_RECEIPT__TRANSACTION_HASH = Internal.createIndex("idx_transaction_receipt__transaction_hash", TransactionReceipt.TRANSACTION_RECEIPT, new OrderField[] { TransactionReceipt.TRANSACTION_RECEIPT.TRANSACTION_HASH }, false);
        public static Index TRANSACTION_RECEIPT_PKEY = Internal.createIndex("transaction_receipt_pkey", TransactionReceipt.TRANSACTION_RECEIPT, new OrderField[] { TransactionReceipt.TRANSACTION_RECEIPT.TRANSACTION_HASH }, true);
    }
}
