/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq.tables;


import io.exflo.postgres.jooq.Indexes;
import io.exflo.postgres.jooq.Keys;
import io.exflo.postgres.jooq.Public;
import io.exflo.postgres.jooq.tables.records.ContractDestroyedRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractDestroyed extends TableImpl<ContractDestroyedRecord> {

    private static final long serialVersionUID = -1040166021;

    /**
     * The reference instance of <code>public.contract_destroyed</code>
     */
    public static final ContractDestroyed CONTRACT_DESTROYED = new ContractDestroyed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContractDestroyedRecord> getRecordType() {
        return ContractDestroyedRecord.class;
    }

    /**
     * The column <code>public.contract_destroyed.address</code>.
     */
    public final TableField<ContractDestroyedRecord, String> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.CHAR(42).nullable(false), this, "");

    /**
     * The column <code>public.contract_destroyed.refund_address</code>.
     */
    public final TableField<ContractDestroyedRecord, String> REFUND_ADDRESS = createField(DSL.name("refund_address"), org.jooq.impl.SQLDataType.CHAR(42).nullable(false), this, "");

    /**
     * The column <code>public.contract_destroyed.refund_amount</code>.
     */
    public final TableField<ContractDestroyedRecord, BigDecimal> REFUND_AMOUNT = createField(DSL.name("refund_amount"), org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.contract_destroyed.block_hash</code>.
     */
    public final TableField<ContractDestroyedRecord, String> BLOCK_HASH = createField(DSL.name("block_hash"), org.jooq.impl.SQLDataType.CHAR(66).nullable(false), this, "");

    /**
     * The column <code>public.contract_destroyed.block_number</code>.
     */
    public final TableField<ContractDestroyedRecord, Long> BLOCK_NUMBER = createField(DSL.name("block_number"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.contract_destroyed.transaction_hash</code>.
     */
    public final TableField<ContractDestroyedRecord, String> TRANSACTION_HASH = createField(DSL.name("transaction_hash"), org.jooq.impl.SQLDataType.CHAR(66).nullable(false), this, "");

    /**
     * The column <code>public.contract_destroyed.timestamp</code>.
     */
    public final TableField<ContractDestroyedRecord, Timestamp> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.contract_destroyed</code> table reference
     */
    public ContractDestroyed() {
        this(DSL.name("contract_destroyed"), null);
    }

    /**
     * Create an aliased <code>public.contract_destroyed</code> table reference
     */
    public ContractDestroyed(String alias) {
        this(DSL.name(alias), CONTRACT_DESTROYED);
    }

    /**
     * Create an aliased <code>public.contract_destroyed</code> table reference
     */
    public ContractDestroyed(Name alias) {
        this(alias, CONTRACT_DESTROYED);
    }

    private ContractDestroyed(Name alias, Table<ContractDestroyedRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContractDestroyed(Name alias, Table<ContractDestroyedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ContractDestroyed(Table<O> child, ForeignKey<O, ContractDestroyedRecord> key) {
        super(child, key, CONTRACT_DESTROYED);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONTRACT_DESTROYED_PKEY, Indexes.IDX_CONTRACT_DESTROYED__ADDRESS, Indexes.IDX_CONTRACT_DESTROYED__BLOCK_HASH, Indexes.IDX_CONTRACT_DESTROYED__BLOCK_NUMBER_DESC, Indexes.IDX_CONTRACT_DESTROYED__TRANSACTION_HASH);
    }

    @Override
    public UniqueKey<ContractDestroyedRecord> getPrimaryKey() {
        return Keys.CONTRACT_DESTROYED_PKEY;
    }

    @Override
    public List<UniqueKey<ContractDestroyedRecord>> getKeys() {
        return Arrays.<UniqueKey<ContractDestroyedRecord>>asList(Keys.CONTRACT_DESTROYED_PKEY);
    }

    @Override
    public List<ForeignKey<ContractDestroyedRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ContractDestroyedRecord, ?>>asList(Keys.CONTRACT_DESTROYED__CONTRACT_DESTROYED_BLOCK_HASH_FKEY, Keys.CONTRACT_DESTROYED__CONTRACT_DESTROYED_TRANSACTION_HASH_FKEY);
    }

    public BlockHeader blockHeader() {
        return new BlockHeader(this, Keys.CONTRACT_DESTROYED__CONTRACT_DESTROYED_BLOCK_HASH_FKEY);
    }

    public Transaction transaction() {
        return new Transaction(this, Keys.CONTRACT_DESTROYED__CONTRACT_DESTROYED_TRANSACTION_HASH_FKEY);
    }

    @Override
    public ContractDestroyed as(String alias) {
        return new ContractDestroyed(DSL.name(alias), this);
    }

    @Override
    public ContractDestroyed as(Name alias) {
        return new ContractDestroyed(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractDestroyed rename(String name) {
        return new ContractDestroyed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContractDestroyed rename(Name name) {
        return new ContractDestroyed(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, BigDecimal, String, Long, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
