/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq.tables;


import io.exflo.postgres.jooq.Public;
import io.exflo.postgres.jooq.tables.records.FungibleTokenTransferRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FungibleTokenTransfer extends TableImpl<FungibleTokenTransferRecord> {

    private static final long serialVersionUID = 657608405;

    /**
     * The reference instance of <code>public.fungible_token_transfer</code>
     */
    public static final FungibleTokenTransfer FUNGIBLE_TOKEN_TRANSFER = new FungibleTokenTransfer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FungibleTokenTransferRecord> getRecordType() {
        return FungibleTokenTransferRecord.class;
    }

    /**
     * The column <code>public.fungible_token_transfer.id</code>.
     */
    public final TableField<FungibleTokenTransferRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.fungible_token_transfer.contract_address</code>.
     */
    public final TableField<FungibleTokenTransferRecord, String> CONTRACT_ADDRESS = createField(DSL.name("contract_address"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.fungible_token_transfer.from</code>.
     */
    public final TableField<FungibleTokenTransferRecord, String> FROM = createField(DSL.name("from"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.fungible_token_transfer.to</code>.
     */
    public final TableField<FungibleTokenTransferRecord, String> TO = createField(DSL.name("to"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.fungible_token_transfer.amount</code>.
     */
    public final TableField<FungibleTokenTransferRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.fungible_token_transfer.block_number</code>.
     */
    public final TableField<FungibleTokenTransferRecord, Long> BLOCK_NUMBER = createField(DSL.name("block_number"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.fungible_token_transfer.block_hash</code>.
     */
    public final TableField<FungibleTokenTransferRecord, String> BLOCK_HASH = createField(DSL.name("block_hash"), org.jooq.impl.SQLDataType.CHAR(66), this, "");

    /**
     * The column <code>public.fungible_token_transfer.block_timestamp</code>.
     */
    public final TableField<FungibleTokenTransferRecord, Timestamp> BLOCK_TIMESTAMP = createField(DSL.name("block_timestamp"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.fungible_token_transfer.transaction_hash</code>.
     */
    public final TableField<FungibleTokenTransferRecord, String> TRANSACTION_HASH = createField(DSL.name("transaction_hash"), org.jooq.impl.SQLDataType.CHAR(66), this, "");

    /**
     * The column <code>public.fungible_token_transfer.transaction_index</code>.
     */
    public final TableField<FungibleTokenTransferRecord, Integer> TRANSACTION_INDEX = createField(DSL.name("transaction_index"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.fungible_token_transfer</code> table reference
     */
    public FungibleTokenTransfer() {
        this(DSL.name("fungible_token_transfer"), null);
    }

    /**
     * Create an aliased <code>public.fungible_token_transfer</code> table reference
     */
    public FungibleTokenTransfer(String alias) {
        this(DSL.name(alias), FUNGIBLE_TOKEN_TRANSFER);
    }

    /**
     * Create an aliased <code>public.fungible_token_transfer</code> table reference
     */
    public FungibleTokenTransfer(Name alias) {
        this(alias, FUNGIBLE_TOKEN_TRANSFER);
    }

    private FungibleTokenTransfer(Name alias, Table<FungibleTokenTransferRecord> aliased) {
        this(alias, aliased, null);
    }

    private FungibleTokenTransfer(Name alias, Table<FungibleTokenTransferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FungibleTokenTransfer(Table<O> child, ForeignKey<O, FungibleTokenTransferRecord> key) {
        super(child, key, FUNGIBLE_TOKEN_TRANSFER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public FungibleTokenTransfer as(String alias) {
        return new FungibleTokenTransfer(DSL.name(alias), this);
    }

    @Override
    public FungibleTokenTransfer as(Name alias) {
        return new FungibleTokenTransfer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FungibleTokenTransfer rename(String name) {
        return new FungibleTokenTransfer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FungibleTokenTransfer rename(Name name) {
        return new FungibleTokenTransfer(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, BigDecimal, Long, String, Timestamp, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
