/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq.tables;


import io.exflo.postgres.jooq.Public;
import io.exflo.postgres.jooq.tables.records.NonFungibleTokenTransferRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NonFungibleTokenTransfer extends TableImpl<NonFungibleTokenTransferRecord> {

    private static final long serialVersionUID = -689089634;

    /**
     * The reference instance of <code>public.non_fungible_token_transfer</code>
     */
    public static final NonFungibleTokenTransfer NON_FUNGIBLE_TOKEN_TRANSFER = new NonFungibleTokenTransfer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NonFungibleTokenTransferRecord> getRecordType() {
        return NonFungibleTokenTransferRecord.class;
    }

    /**
     * The column <code>public.non_fungible_token_transfer.id</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.contract_address</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, String> CONTRACT_ADDRESS = createField(DSL.name("contract_address"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.from</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, String> FROM = createField(DSL.name("from"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.to</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, String> TO = createField(DSL.name("to"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.token_id</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, BigDecimal> TOKEN_ID = createField(DSL.name("token_id"), org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.block_number</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, Long> BLOCK_NUMBER = createField(DSL.name("block_number"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.block_hash</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, String> BLOCK_HASH = createField(DSL.name("block_hash"), org.jooq.impl.SQLDataType.CHAR(66), this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.block_timestamp</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, Timestamp> BLOCK_TIMESTAMP = createField(DSL.name("block_timestamp"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.transaction_hash</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, String> TRANSACTION_HASH = createField(DSL.name("transaction_hash"), org.jooq.impl.SQLDataType.CHAR(66), this, "");

    /**
     * The column <code>public.non_fungible_token_transfer.transaction_index</code>.
     */
    public final TableField<NonFungibleTokenTransferRecord, Integer> TRANSACTION_INDEX = createField(DSL.name("transaction_index"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.non_fungible_token_transfer</code> table reference
     */
    public NonFungibleTokenTransfer() {
        this(DSL.name("non_fungible_token_transfer"), null);
    }

    /**
     * Create an aliased <code>public.non_fungible_token_transfer</code> table reference
     */
    public NonFungibleTokenTransfer(String alias) {
        this(DSL.name(alias), NON_FUNGIBLE_TOKEN_TRANSFER);
    }

    /**
     * Create an aliased <code>public.non_fungible_token_transfer</code> table reference
     */
    public NonFungibleTokenTransfer(Name alias) {
        this(alias, NON_FUNGIBLE_TOKEN_TRANSFER);
    }

    private NonFungibleTokenTransfer(Name alias, Table<NonFungibleTokenTransferRecord> aliased) {
        this(alias, aliased, null);
    }

    private NonFungibleTokenTransfer(Name alias, Table<NonFungibleTokenTransferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> NonFungibleTokenTransfer(Table<O> child, ForeignKey<O, NonFungibleTokenTransferRecord> key) {
        super(child, key, NON_FUNGIBLE_TOKEN_TRANSFER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public NonFungibleTokenTransfer as(String alias) {
        return new NonFungibleTokenTransfer(DSL.name(alias), this);
    }

    @Override
    public NonFungibleTokenTransfer as(Name alias) {
        return new NonFungibleTokenTransfer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NonFungibleTokenTransfer rename(String name) {
        return new NonFungibleTokenTransfer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NonFungibleTokenTransfer rename(Name name) {
        return new NonFungibleTokenTransfer(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, BigDecimal, Long, String, Timestamp, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
