/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq.tables;


import io.exflo.postgres.jooq.Public;
import io.exflo.postgres.jooq.enums.DeltaType;
import io.exflo.postgres.jooq.tables.records.RewardRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reward extends TableImpl<RewardRecord> {

    private static final long serialVersionUID = -917766570;

    /**
     * The reference instance of <code>public.reward</code>
     */
    public static final Reward REWARD = new Reward();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RewardRecord> getRecordType() {
        return RewardRecord.class;
    }

    /**
     * The column <code>public.reward.id</code>.
     */
    public final TableField<RewardRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.reward.delta_type</code>.
     */
    public final TableField<RewardRecord, DeltaType> DELTA_TYPE = createField(DSL.name("delta_type"), org.jooq.impl.SQLDataType.VARCHAR.asEnumDataType(io.exflo.postgres.jooq.enums.DeltaType.class), this, "");

    /**
     * The column <code>public.reward.to</code>.
     */
    public final TableField<RewardRecord, String> TO = createField(DSL.name("to"), org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.reward.amount</code>.
     */
    public final TableField<RewardRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.reward.block_number</code>.
     */
    public final TableField<RewardRecord, Long> BLOCK_NUMBER = createField(DSL.name("block_number"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.reward.block_hash</code>.
     */
    public final TableField<RewardRecord, String> BLOCK_HASH = createField(DSL.name("block_hash"), org.jooq.impl.SQLDataType.CHAR(66), this, "");

    /**
     * The column <code>public.reward.block_timestamp</code>.
     */
    public final TableField<RewardRecord, Timestamp> BLOCK_TIMESTAMP = createField(DSL.name("block_timestamp"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.reward</code> table reference
     */
    public Reward() {
        this(DSL.name("reward"), null);
    }

    /**
     * Create an aliased <code>public.reward</code> table reference
     */
    public Reward(String alias) {
        this(DSL.name(alias), REWARD);
    }

    /**
     * Create an aliased <code>public.reward</code> table reference
     */
    public Reward(Name alias) {
        this(alias, REWARD);
    }

    private Reward(Name alias, Table<RewardRecord> aliased) {
        this(alias, aliased, null);
    }

    private Reward(Name alias, Table<RewardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Reward(Table<O> child, ForeignKey<O, RewardRecord> key) {
        super(child, key, REWARD);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Reward as(String alias) {
        return new Reward(DSL.name(alias), this);
    }

    @Override
    public Reward as(Name alias) {
        return new Reward(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reward rename(String name) {
        return new Reward(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reward rename(Name name) {
        return new Reward(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, DeltaType, String, BigDecimal, Long, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
