version: '3.7'

networks:
  net:
    driver: bridge

volumes:

  postgres:
    driver: local

  zookeeper-data:
    driver: local

  zookeeper-log:
    driver: local

  kafka-data:
    driver: local

  besu:
    driver: local

services:

#  zookeeper:
#    image: confluentinc/cp-zookeeper:5.3.1
#    restart: unless-stopped
#    volumes:
#      - zookeeper-data:/var/lib/zookeeper/data
#      - zookeeper-log:/var/lib/zookeeper/log
#    networks:
#      - net
#    ports:
#      - 2181:2181
#      - 9585:9585
#    environment:
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_JMX_PORT: 9585
#
#  kafka:
#    image: confluentinc/cp-kafka:5.3.1
#    restart: unless-stopped
#    hostname: kafka
#    depends_on:
#      - zookeeper
#    volumes:
#      - kafka-data:/var/lib/kafka
#    networks:
#      - net
#    ports:
#      - 9092:9092
#      - 9586:9586
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_BROKER_ID: 1
#      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
#      KAFKA_COMPRESSION_TYPE: "zstd"
#      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 52428800
#      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 10485760
#      KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS: 120000
#      KAFKA_MESSAGE_MAX_BYTES: 52428800
#      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
#      KAFKA_TOPIC_DELETE_ENABLE: 'true'
#      CONFLUENT_METRICS_ENABLE: 'false'
#      KAFKA_JMX_PORT: 9586
#
#  kafkahq:
#    image: tchiotludo/kafkahq
#    networks:
#      - net
#    ports:
#      - 8080:8080
#    links:
#      - kafka
#    environment:
#      KAFKAHQ_CONFIGURATION: |
#        kafkahq:
#          connections:
#            docker-kafka-server:
#              properties:
#                bootstrap.servers: "kafka:9092"


  postgres:
    image: postgres:12
    restart: unless-stopped
    shm_size: 4g
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_USER: exflo
      POSTGRES_PASSWORD: exflo
      POSTGRES_DB: exflo

  pgweb:
    image: sosedoff/pgweb:0.11.5
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - postgres
    ports:
      - 8082:8082
    command: "/usr/bin/pgweb --bind=0.0.0.0 --listen=8082 --url postgres://exflo:exflo@postgres:5432/exflo?sslmode=disable"

  besu:
    image: 41north/exflo
    networks:
      - net
    depends_on:
      - postgres
    volumes:
      - besu:/opt/besu/data
    environment:
      BESU_LOGGING: info
      BESU_NETWORK: ROPSTEN
      BESU_BOOT_NODES: "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303"
      BESU_SYNC_MODE: FULL
      BESU_DATA_PATH: /opt/besu/data
      BESU_PLUGIN_EXFLO_KAFKA_ENABLED: 'false'
      BESU_PLUGIN_EXFLO_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BESU_PLUGIN_EXFLO_POSTGRES_ENABLED: 'true'
      BESU_PLUGIN_EXFLO_POSTGRES_JDBC_URL: jdbc:postgresql://postgres/exflo?user=exflo&password=exflo