/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq.enums;


import io.exflo.postgres.jooq.Public;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum DeltaType implements EnumType {

    BLOCK_REWARD("BLOCK_REWARD"),

    OMMER_REWARD("OMMER_REWARD"),

    TX("TX"),

    TX_FEE("TX_FEE"),

    INTERNAL_TX("INTERNAL_TX"),

    TOKEN_TRANSFER("TOKEN_TRANSFER"),

    CONTRACT_CREATION("CONTRACT_CREATION"),

    CONTRACT_DESTRUCTION("CONTRACT_DESTRUCTION");

    private final String literal;

    private DeltaType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "delta_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
