/*
 * This file is generated by jOOQ.
 */
package io.exflo.postgres.jooq.tables.records;


import io.exflo.postgres.jooq.enums.DeltaType;
import io.exflo.postgres.jooq.tables.BalanceDelta;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceDeltaRecord extends UpdatableRecordImpl<BalanceDeltaRecord> implements Record12<Long, DeltaType, String, String, String, BigDecimal, BigDecimal, Long, String, String, Integer, Timestamp> {

    private static final long serialVersionUID = 2137993143;

    /**
     * Setter for <code>public.balance_delta.id</code>.
     */
    public BalanceDeltaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.balance_delta.delta_type</code>.
     */
    public BalanceDeltaRecord setDeltaType(DeltaType value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.delta_type</code>.
     */
    public DeltaType getDeltaType() {
        return (DeltaType) get(1);
    }

    /**
     * Setter for <code>public.balance_delta.contract_address</code>.
     */
    public BalanceDeltaRecord setContractAddress(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.contract_address</code>.
     */
    public String getContractAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.balance_delta.from</code>.
     */
    public BalanceDeltaRecord setFrom(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.from</code>.
     */
    public String getFrom() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.balance_delta.to</code>.
     */
    public BalanceDeltaRecord setTo(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.to</code>.
     */
    public String getTo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.balance_delta.amount</code>.
     */
    public BalanceDeltaRecord setAmount(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.balance_delta.token_id</code>.
     */
    public BalanceDeltaRecord setTokenId(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.token_id</code>.
     */
    public BigDecimal getTokenId() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.balance_delta.block_number</code>.
     */
    public BalanceDeltaRecord setBlockNumber(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.block_number</code>.
     */
    public Long getBlockNumber() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.balance_delta.block_hash</code>.
     */
    public BalanceDeltaRecord setBlockHash(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.balance_delta.transaction_hash</code>.
     */
    public BalanceDeltaRecord setTransactionHash(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.transaction_hash</code>.
     */
    public String getTransactionHash() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.balance_delta.transaction_index</code>.
     */
    public BalanceDeltaRecord setTransactionIndex(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.transaction_index</code>.
     */
    public Integer getTransactionIndex() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.balance_delta.block_timestamp</code>.
     */
    public BalanceDeltaRecord setBlockTimestamp(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.block_timestamp</code>.
     */
    public Timestamp getBlockTimestamp() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, DeltaType, String, String, String, BigDecimal, BigDecimal, Long, String, String, Integer, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, DeltaType, String, String, String, BigDecimal, BigDecimal, Long, String, String, Integer, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BalanceDelta.BALANCE_DELTA.ID;
    }

    @Override
    public Field<DeltaType> field2() {
        return BalanceDelta.BALANCE_DELTA.DELTA_TYPE;
    }

    @Override
    public Field<String> field3() {
        return BalanceDelta.BALANCE_DELTA.CONTRACT_ADDRESS;
    }

    @Override
    public Field<String> field4() {
        return BalanceDelta.BALANCE_DELTA.FROM;
    }

    @Override
    public Field<String> field5() {
        return BalanceDelta.BALANCE_DELTA.TO;
    }

    @Override
    public Field<BigDecimal> field6() {
        return BalanceDelta.BALANCE_DELTA.AMOUNT;
    }

    @Override
    public Field<BigDecimal> field7() {
        return BalanceDelta.BALANCE_DELTA.TOKEN_ID;
    }

    @Override
    public Field<Long> field8() {
        return BalanceDelta.BALANCE_DELTA.BLOCK_NUMBER;
    }

    @Override
    public Field<String> field9() {
        return BalanceDelta.BALANCE_DELTA.BLOCK_HASH;
    }

    @Override
    public Field<String> field10() {
        return BalanceDelta.BALANCE_DELTA.TRANSACTION_HASH;
    }

    @Override
    public Field<Integer> field11() {
        return BalanceDelta.BALANCE_DELTA.TRANSACTION_INDEX;
    }

    @Override
    public Field<Timestamp> field12() {
        return BalanceDelta.BALANCE_DELTA.BLOCK_TIMESTAMP;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public DeltaType component2() {
        return getDeltaType();
    }

    @Override
    public String component3() {
        return getContractAddress();
    }

    @Override
    public String component4() {
        return getFrom();
    }

    @Override
    public String component5() {
        return getTo();
    }

    @Override
    public BigDecimal component6() {
        return getAmount();
    }

    @Override
    public BigDecimal component7() {
        return getTokenId();
    }

    @Override
    public Long component8() {
        return getBlockNumber();
    }

    @Override
    public String component9() {
        return getBlockHash();
    }

    @Override
    public String component10() {
        return getTransactionHash();
    }

    @Override
    public Integer component11() {
        return getTransactionIndex();
    }

    @Override
    public Timestamp component12() {
        return getBlockTimestamp();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public DeltaType value2() {
        return getDeltaType();
    }

    @Override
    public String value3() {
        return getContractAddress();
    }

    @Override
    public String value4() {
        return getFrom();
    }

    @Override
    public String value5() {
        return getTo();
    }

    @Override
    public BigDecimal value6() {
        return getAmount();
    }

    @Override
    public BigDecimal value7() {
        return getTokenId();
    }

    @Override
    public Long value8() {
        return getBlockNumber();
    }

    @Override
    public String value9() {
        return getBlockHash();
    }

    @Override
    public String value10() {
        return getTransactionHash();
    }

    @Override
    public Integer value11() {
        return getTransactionIndex();
    }

    @Override
    public Timestamp value12() {
        return getBlockTimestamp();
    }

    @Override
    public BalanceDeltaRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value2(DeltaType value) {
        setDeltaType(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value3(String value) {
        setContractAddress(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value4(String value) {
        setFrom(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value5(String value) {
        setTo(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value6(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value7(BigDecimal value) {
        setTokenId(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value8(Long value) {
        setBlockNumber(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value9(String value) {
        setBlockHash(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value10(String value) {
        setTransactionHash(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value11(Integer value) {
        setTransactionIndex(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord value12(Timestamp value) {
        setBlockTimestamp(value);
        return this;
    }

    @Override
    public BalanceDeltaRecord values(Long value1, DeltaType value2, String value3, String value4, String value5, BigDecimal value6, BigDecimal value7, Long value8, String value9, String value10, Integer value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BalanceDeltaRecord
     */
    public BalanceDeltaRecord() {
        super(BalanceDelta.BALANCE_DELTA);
    }

    /**
     * Create a detached, initialised BalanceDeltaRecord
     */
    public BalanceDeltaRecord(Long id, DeltaType deltaType, String contractAddress, String from, String to, BigDecimal amount, BigDecimal tokenId, Long blockNumber, String blockHash, String transactionHash, Integer transactionIndex, Timestamp blockTimestamp) {
        super(BalanceDelta.BALANCE_DELTA);

        set(0, id);
        set(1, deltaType);
        set(2, contractAddress);
        set(3, from);
        set(4, to);
        set(5, amount);
        set(6, tokenId);
        set(7, blockNumber);
        set(8, blockHash);
        set(9, transactionHash);
        set(10, transactionIndex);
        set(11, blockTimestamp);
    }
}
